name: Deploy to S3

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3
        run: |
          # Sync all files, setting appropriate content types
          aws s3 sync deploy/ s3://elle.lgbt \
            --delete \
            --exclude "*" \
            --include "*.html" \
            --include "*.css" \
            --include "*.js" \
            --include "*.svg" \
            --content-type "text/html" \
            --content-type "text/css:*.css" \
            --content-type "application/javascript:*.js" \
            --content-type "image/svg+xml:*.svg" \
            --content-disposition "inline"

          # Remove .html extensions from HTML files in S3
          aws s3 ls s3://elle.lgbt --recursive | grep '\.html$' | awk '{print $4}' | while read -r key; do
            newkey="${key%.html}"
            if [ "$key" != "$newkey" ]; then
              aws s3 cp "s3://elle.lgbt/$key" "s3://elle.lgbt/$newkey" \
                --content-type "text/html" \
                --content-disposition "inline" \
                --metadata-directive REPLACE
              aws s3 rm "s3://elle.lgbt/$key"
            fi
          done